apiVersion: v1
kind: Service
metadata:
  name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  namespace: TODO_K8S_NAMESPACE
  labels:
    app: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
spec:
  ports:
    - port: TODO_K8S_SERVICE_PORT
      targetPort: 9091
  selector:
    app: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  namespace: TODO_K8S_NAMESPACE
  labels:
    app: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  template:
    metadata:
      labels:
        app: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
    spec:
      securityContext:
        runAsUser: 2000
      containers:
      - env:
        - name: AZURE_KV_ENABLED
          value: "true"
        - name: AZURE_KV_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
        - name: AZURE_KV_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
        - name: AZURE_KV_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              key: client-key
              name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
        - name: AZURE_KV_TENANT_ID
          valueFrom:
            secretKeyRef:
              key: tenant-id
              name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
        - name: SPRING_CLOUD_CONFIG_FAIL-FAST
          value: "true"
        - name: SPRING_CLOUD_CONFIG_RETRY_MAX-ATTEMPTS
          value: "30"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://khala-config.config.svc.cluster.local:8888/
        - name: SPRING_PROFILES_ACTIVE
          value: $PROFILE
        image: $REGISTRY/ms-ux-distribucion-de-costos-ejecuta-proceso-pga:$TAG
        name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
        livenessProbe:
          httpGet:
            path: /ms-ux-distribucion-de-costos-ejecuta-proceso-pga/v1/health
            port: 9091
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ms-ux-distribucion-de-costos-ejecuta-proceso-pga/v1/health
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 9091
          name: http
        resources:
          limits:
            cpu: 900m
            memory: 1200Mi
          requests:
            cpu: 100m
            memory: 700Mi
      imagePullSecrets:
        - name: regsecret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  namespace: TODO_K8S_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ms-ux-distribucion-de-costos-ejecuta-proceso-pga-ingress-nginx
  namespace: TODO_K8S_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ms-ux-distribucion-de-costos-ejecuta-proceso-pga
          servicePort: TODO_K8S_SERVICE_PORT
        path: TODO_K8S_INGRESS_PATH

#- *********Generated from : https://kuntur.digital.pacifico.com.pe/************